version: "3.9"

services:
  blsopro_backend:
    image: blsopro_backend
    build: .
    container_name: blsopro_backend
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/blsopro
      - SPRING_DATASOURCE_USERNAME=blsopro
      - SPRING_DATASOURCE_PASSWORD=blsopro123
    depends_on:
      - postgresql

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=blsopro
      - POSTGRESQL_USERNAME=blsopro
      - POSTGRESQL_PASSWORD=blsopro123
 
    volumes:
      - postgresql_data:/bitnami/postgresql


volumes:
  postgresql_data:
    
